name: Build & Publish GOL Snapshots

on:
  workflow_dispatch:
    workflow_run:
      workflows: [ "Build & Publish PBF Snapshots" ]
      types: [ completed ]

env:
  REMOTE_NAME: openplanetdata-r2

jobs:
  gol:
    runs-on: openplanetdata-hetzner-ccx43

    outputs:
      tag: ${{ steps.date.outputs.tag }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Install gol
        run: |
          set -euo pipefail

          tmp=$(mktemp -d)
          url=$(curl -sSL https://api.github.com/repos/clarisma/gol-tool/releases/latest \
                  | grep -oP '"browser_download_url":\s*"\K[^"]+gol-tool-[^"]+\.zip')
          curl -L "$url" -o "$tmp/gol.zip"

          # unpack under /opt
          sudo unzip -q "$tmp/gol.zip" -d /opt

          # /opt/gol-tool → /opt/gol-tool-<version>
          latest=$(ls -d /opt/gol-tool-* | sort -V | tail -n1)
          sudo ln -sfn "$latest" /opt/gol-tool

          # tiny wrapper on PATH
          sudo tee /usr/local/bin/gol >/dev/null <<'EOF'
          #!/usr/bin/env bash
          exec /opt/gol-tool/bin/gol "$@"
          EOF
          sudo chmod +x /usr/local/bin/gol

          gol --version

      - name: Install rclone
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.config/rclone
          printf '%s' "$RCLONE_CONFIG_DATA" > ~/.config/rclone/rclone.conf
          command -v rclone >/dev/null || curl https://rclone.org/install.sh | sudo bash

      - name: Download latest published PBF
        run: |
          time curl -L https://download.openplanetdata.com/osm/planet/pbf/planet-latest.osm.pbf \
            -o "planet-${{ steps.date.outputs.tag }}.osm.pbf"

      - name: Build GOL variant
        run: |
          g="planet-${{ steps.date.outputs.tag }}.osm.gol"
          p="planet-${{ steps.date.outputs.tag }}.osm.pbf"
          time gol build "$g" "$p"
          shasum -a 256 "$g" >"$g.sha256"
          stat -c '%s %W %Z' "$g" | \
            awk '{print "{\"created\":"($2==0?$3:$2)",\"size\":"$1"}"}' >"$g.metadata"

      - name: Upload GOL files to R2
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          rclone copyto "planet-${{ steps.date.outputs.tag }}.osm.gol"          "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol"
          rclone copyto "planet-${{ steps.date.outputs.tag }}.osm.gol.metadata" "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol.metadata"
          rclone copyto "planet-${{ steps.date.outputs.tag }}.osm.gol.sha256"   "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol.sha256"
