name: Build & Publish PBF Snapshots

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  REMOTE_NAME: openplanetdata-r2

jobs:
  pbf:
    runs-on: openplanetdata-cortex

    outputs:
      tag: ${{ steps.date.outputs.tag }}

    steps:
      - name: Set date tag
        id: date
        run: echo "tag=$(date '+%Y%m%d')" >>"$GITHUB_OUTPUT"

      - name: Install core tools (skip if already present)
        shell: bash
        run: |
          need_install() { ! command -v "$1" >/dev/null 2>&1; }
          pkgs=()
          need_install aria2c    && pkgs+=(aria2)
          need_install osmium    && pkgs+=(osmium-tool)
          need_install osmupdate && pkgs+=(osmctools)
          need_install unzip     && pkgs+=(unzip)
          
          if ((${#pkgs[@]})); then
            sudo dnf -y install "${pkgs[@]}"
          else
            echo "All required packages already present."
          fi
      - name: Install rclone (skip if already present)
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          if ! command -v rclone >/dev/null 2>&1; then
            curl https://rclone.org/install.sh | sudo bash
          fi
          mkdir -p ~/.config/rclone
          printf '%s' "$RCLONE_CONFIG_DATA" > ~/.config/rclone/rclone.conf
          rclone --version

      - name: Download latest OSM planet
        run: |
          aria2c --seed-time=0 \
            https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.torrent \
            --index-out=1=planet-latest.osm.pbf

      - name: Generate new PBF version with latest changes
        run: |
          f="planet-${{ steps.date.outputs.tag }}.osm.pbf"
          time osmupdate planet-latest.osm.pbf "$f" --hour --verbose
          rm planet-latest.osm.pbf
          sha256sum "$f" >"$f.sha256"
          stat -c '%s %W %Z' "$f" | \
            awk '{print "{\"created\":"($2==0?$3:$2)",\"size\":"$1"}"}' >"$f.metadata"

      - name: Upload PBF files to R2
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          date=${{ steps.date.outputs.tag }}
          rclone copyto "planet-$date.osm.pbf"          "$REMOTE_NAME:openplanetdata/osm/planet/pbf/planet-latest.osm.pbf"
          rclone copyto "planet-$date.osm.pbf.metadata" "$REMOTE_NAME:openplanetdata/osm/planet/pbf/planet-latest.osm.pbf.metadata"
          rclone copyto "planet-$date.osm.pbf.sha256"   "$REMOTE_NAME:openplanetdata/osm/planet/pbf/planet-latest.osm.pbf.sha256"

      - name: Cleanup downloaded and generated files
        if: always()
        run: |
          rm -f planet-*.osm.pbf planet-*.osm.pbf.{sha256,metadata}
          find /tmp -name "tmp.*" -user "$USER" -delete 2>/dev/null || true
