name: Build & Publish OSM Snapshots

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  REMOTE_NAME: openplanetdata-r2

jobs:
  planet_pbf:
    runs-on: openplanetdata-hetzner-ccx33

    outputs:
      tag: ${{ steps.date.outputs.tag }}

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Set date tag
        id: date
        run: echo "tag=$(date '+%Y%m%d')" >>"$GITHUB_OUTPUT"

      - name: Install core tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 osmctools osmium-tool unzip

      - name: Install rclone
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.config/rclone
          printf '%s' "$RCLONE_CONFIG_DATA" > ~/.config/rclone/rclone.conf
          curl https://rclone.org/install.sh | sudo bash
          rclone --version

      - name: Download latest OSM planet
        run: |
          aria2c --seed-time=0 \
            https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.torrent \
            --index-out=1=planet-latest.osm.pbf

      - name: Generate new PBF version with latest changes
        run: |
          f="planet-${{ steps.date.outputs.tag }}.osm.pbf"
          time osmupdate planet-latest.osm.pbf "$f" --hour --verbose
          rm planet-latest.osm.pbf
          shasum -a 256 "$f" >"$f.sha256"
          stat -c '%s %W %Z' "$f" | \
            awk '{print "{\"created\":"($2==0?$3:$2)",\"size\":"$1"}"}' >"$f.metadata"

      - name: Upload PBF files to R2
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          date=${{ steps.date.outputs.tag }}
          rclone copyto "planet-$date.osm.pbf"          "$REMOTE_NAME:osm/planet/pbf/planet-latest.osm.pbf"
          rclone copyto "planet-$date.osm.pbf.metadata" "$REMOTE_NAME:osm/planet/pbf/planet-latest.osm.pbf.metadata"
          rclone copyto "planet-$date.osm.pbf.sha256"   "$REMOTE_NAME:osm/planet/pbf/osm-planet-latest.pbf.sha256"

  planet_gol:
    needs: planet_pbf
    runs-on: openplanetdata-hetzner-ccx53
    env:
      DATE_TAG: ${{ needs.planet_pbf.outputs.tag }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Install gol
        run: |
          set -euo pipefail

          tmp=$(mktemp -d)
          url=$(curl -sSL https://api.github.com/repos/clarisma/gol-tool/releases/latest \
                  | grep -oP '"browser_download_url":\s*"\K[^"]+gol-tool-[^"]+\.zip')
          curl -L "$url" -o "$tmp/gol.zip"

          # unpack under /opt
          sudo unzip -q "$tmp/gol.zip" -d /opt

          # /opt/gol-tool → /opt/gol-tool-<version>
          latest=$(ls -d /opt/gol-tool-* | sort -V | tail -n1)
          sudo ln -sfn "$latest" /opt/gol-tool

          # tiny wrapper on PATH
          sudo tee /usr/local/bin/gol >/dev/null <<'EOF'
          #!/usr/bin/env bash
          exec /opt/gol-tool/bin/gol "$@"
          EOF
          sudo chmod +x /usr/local/bin/gol

          gol --version

      - name: Install rclone
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.config/rclone
          printf '%s' "$RCLONE_CONFIG_DATA" > ~/.config/rclone/rclone.conf
          command -v rclone >/dev/null || curl https://rclone.org/install.sh | sudo bash

      - name: Download latest published PBF
        run: |
          curl -L https://download.openplanetdata.com/osm/planet/pbf/planet-latest.osm.pbf \
            -o "planet-${DATE_TAG}.osm.pbf"

      - name: Build GOL variant
        run: |
          g="planet-${DATE_TAG}.osm.gol"
          p="planet-${DATE_TAG}.osm.pbf"
          time gol build "$g" "$p"
          shasum -a 256 "$g" >"$g.sha256"
          stat -c '%s %W %Z' "$g" | \
            awk '{print "{\"created\":"($2==0?$3:$2)",\"size\":"$1"}"}' >"$g.metadata"

      - name: Upload GOL files to R2
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          rclone copyto "planet-${DATE_TAG}.osm.gol"          "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol"
          rclone copyto "planet-${DATE_TAG}.osm.gol.metadata" "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol.metadata"
          rclone copyto "planet-${DATE_TAG}.osm.gol.sha256"   "$REMOTE_NAME:osm/planet/gol/planet-latest.osm.gol.sha256"
